baseURL = "https://rhussmann.com/"
languageCode = "en-us"
title = "rhussmann.com"
theme = "charaka"
googleAnalytics = "G-N56GF8L37Z"

[params]

[[params.social]]
  url = "https://twitter.com/rhussmann"
  fa_icon = "fab fa-twitter"

[[params.social]]
  url = "https://github.com/rhussmann"
  fa_icon = "fab fa-github"
