baseURL = "https://rhussmann.com"
languageCode = "en-us"
title = "rhussmann.com"
theme = "charaka"
googleAnalytics = "G-N56GF8L37Z"

[markup.goldmark.renderer]
  unsafe = true

[params]

[[params.social]]
  url = "https://twitter.com/rhussmann"
  fa_icon = "fab fa-twitter"

[[params.social]]
  url = "https://github.com/rhussmann"
  fa_icon = "fab fa-github"

[[params.social]]
  url = "https://mastodon.social/@rhussmann"
  fa_icon = "fab fa-mastodon"
