baseURL = "https://rhussmann.com"
languageCode = "en-us"
title = "rhussmann.com"
theme = "hugo-kiera"
googleAnalytics = "G-N56GF8L37Z"

[params.author]	
  name = "Ricky Hussmann"
  github = "rhussmann"
  linkedin = "rhussmann"
  mastodon = "mastodon.social/@rhussmann"
