name: Deploy
on: ["push"]
permissions:
  id-token: write
  contents: read

jobs:
  deploy_blog:
    runs-on: ubuntu-latest
    name: Deploy blog.rhussmann.com
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.81.0'

      - name: Build
        run: hugo --minify

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::140106038064:role/GithubActionsRole
          role-session-name: samplerolesession
          aws-region: us-east-1

      - name: Copy assets to S3
        run: aws s3 sync --size-only ./public/ s3://rhussmann.com/
